### ISSUE TITLE
Nothing showing on Windows 10

### ISSUE THREAD

**Issue by dksim** [matthew-matvei/freeman#21]
### Steps to reproduce

Run the application after installation

### Expected behaviour

Show folder contents

### Current behaviour

No file showing and not possible to change folder

### System information

- Operating system: Windows 10
- Version of FreeMAN: 0.8.1

**Comment by matthew-matvei** [comment]
Hi @dksim 

I currently don't see this behaviour after installing v0.8.1. It's possible your antivirus has gotten trigger-happy and has tripped up the setup process.

Do you get any errors? (to capture any silent ones, you could try starting the program from powershell (with command-line `--verbose` if at first you see nothing) or hitting F12 from inside the application which will show you the developer tools. From there you could even inspect the DOM in the 'Elements' tab. Note that there are currently numerous `TypeError`s relating to Electron's callbacks registry on Windows, but this is not affecting end behaviour.

In the meantime, you could also share anything interesting in the log file that should be in `%userprofile%\AppData\Roaming\FreeMAN\log.log`.

Also, you could try building the program yourself (really not tricky, see [README](https://github.com/matthew-matvei/freeman#getting-started) after installing [NodeJS](https://nodejs.org/en/download/)) to see if there's any different behaviour (you might feel more comfortable allowing an exception in your antivirus whilst debugging open source code you've built yourself)

**Comment by dksim** [comment]
Well the first error is of the type

> Uncaught (in promise) Error: EINVAL: invalid argument, lstat

and then a bunch of error of the type

> [error] TypeError: this.on is not a function
>     at once (events.js:342:8)
>     at CallbacksRegistry.apply (\freeman\resources\electron.asar\common\api\callbacks-registry.js:46:25)
>     at EventEmitter.ipcRenderer.on (\freeman\resources\electron.asar\renderer\api\remote.js:261:21)
>     at emitThree (events.js:135:13)
>     at EventEmitter.emit (events.js:216:7)
>

**Comment by dksim** [comment]
From powershell with verbose I also get a few  

> Cannot parse settings from....

**Comment by matthew-matvei** [comment]
Sorry, GH gave me no notification about these messages.

The callbacks registry are known errors that occur on Windows that cause no real loss in functionality. You should get the `Cannot parse settings from...` in verbose mode (as you haven't placed a settings file to configure the application there)

The `EINVAL` is a new one though, I don't think I've seen it before. If this is still an issue, could you post the relevant section of the log file that contains that error? I'll see if I can find that same error on my end.

Currently, the app doesn't handle folders that contain folders / files with read-only permissions very well (there is a PR waiting to be re-opened looking at handling this better). Is it possible for you to place any folders / files you might not have full read-write access to from your home folder elsewhere temporarily (even if it's just within a `temp` folder that you have full read / write access to. The app should start up at `C:\Users\{userName}\`.

**Comment by matthew-matvei** [comment]
@dksim 

If you're accustomed to building this project, try building the latest of `check-accessibility` branch. If that works, `git reset --hard 5bb0a06c60fbb18c41642e6e1b288f22fa10d15f` to before the potential fix and check that that doesn't work.

The latest change on that branch is that an initial lstat on a given directory item would fail if the user didn't have permissions to the folder, now that case should be handled. I suppose it's possible there's a folder in your home directory you don't have full permissions to view?

**Comment by dksim** [comment]
I uninstalled and reinstalled the application and it seems to work now. Not sure what changed.

**Comment by matthew-matvei** [comment]
Glad to hear it got sorted
